phrase:
  access_token: 7dc802029b965bf3ee4a497a4eefa4b71f824e5db23a0b04c0cfffb972f44b05
  project_id: 39691242852b1ca501ab9c37e742dd67
  push:
    sources:
    - file: ./locale/<locale_name>.json
      params:
        file_format: simple_json
  pull:
    targets:
    - file: ./locale/<locale_name>.json
      params:
        file_format: simple_json
