phrase:
  access_token: "7dc802029b965bf3ee4a497a4eefa4b71f824e5db23a0b04c0cfffb972f44b05"
  project_id: 74c513cde1864f3737f329c1f680ac2b
  push:
  sources:
  - file: "./src/locales/en-US.json"
    params:
      file_format: simple_json
      locale_id: 473d7c3c6a76b3152be683c6c5cbf95e
      update_Translation: true
pull:
  targets:
  - file: "./src/locales/es-ES.json"
    params:
      file_format: simple_json
      locale_id: a3e8ed5259a0b921ad3791433a123c38
  - file: "./src/locales/ca-ES.json"
    params:
      file_format: simple_json
      locale_id: 02b5dc00faaed69a1ba55d5187716239
